<?php
include_once 'Circle.php';
class Cylinder extends Circle{
    public int $height;
    public function __construct(string $name, int $radius, string $color, int $height)
    {
        parent::__construct($name, $radius, $color);
        $this->height = $height;
    }
    public function calculatePerimeter(): int
    {
        return parent::calculatePerimeter()*2+parent::calculatePerimeter()*$this->height; // TODO: Change the autogenerated stub
    }

    public function calculateArea(): int
    {
        return parent::calculateArea()*$this->height; // TODO: Change the autogenerated stub
    }
}